/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/gateway/anthropic/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anthropic API, proxied (Claude Code, Copilot CLI)
         * @description Set `ANTHROPIC_BASE_URL` (Claude Code) or `COPILOT_PROVIDER_BASE_URL` with `COPILOT_PROVIDER_TYPE=anthropic` (Copilot CLI) to `<host>/gateway/anthropic`. Forwards `v1/messages`, `v1/messages/count_tokens` and `v1/models`; bodies and streams pass through unchanged. The client's key is forwarded, never stored.
         */
        get: operations["gateway_anthropic_get"];
        put?: never;
        /**
         * Anthropic API, proxied (Claude Code, Copilot CLI)
         * @description Set `ANTHROPIC_BASE_URL` (Claude Code) or `COPILOT_PROVIDER_BASE_URL` with `COPILOT_PROVIDER_TYPE=anthropic` (Copilot CLI) to `<host>/gateway/anthropic`. Forwards `v1/messages`, `v1/messages/count_tokens` and `v1/models`; bodies and streams pass through unchanged. The client's key is forwarded, never stored.
         */
        post: operations["gateway_anthropic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/openai/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAI API, proxied (Copilot Chat Custom Endpoint, Copilot CLI)
         * @description Use `<host>/gateway/openai/v1` as the OpenAI-compatible base URL. Forwards `v1/chat/completions` and `v1/models`; bodies and streams pass through unchanged.
         */
        get: operations["gateway_openai_get"];
        put?: never;
        /**
         * OpenAI API, proxied (Copilot Chat Custom Endpoint, Copilot CLI)
         * @description Use `<host>/gateway/openai/v1` as the OpenAI-compatible base URL. Forwards `v1/chat/completions` and `v1/models`; bodies and streams pass through unchanged.
         */
        post: operations["gateway_openai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Costs
         * @description Spend over time, grouped by model, client or service.
         */
        get: operations["costs_v1_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Info
         * @description Whether the database holds the startup sample data, real data, or both.
         */
        get: operations["data_info_v1_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evals/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Eval Runs
         * @description Eval runs, newest first.
         */
        get: operations["list_eval_runs_v1_evals_runs_get"];
        put?: never;
        /**
         * Create Eval Run
         * @description Record an eval run (posted by `lucentpad eval`).
         */
        post: operations["create_eval_run_v1_evals_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evals/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Run */
        get: operations["get_eval_run_v1_evals_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gateway/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gateway Summary
         * @description Per-client sessions, turns, tokens and cost over the window.
         */
        get: operations["gateway_summary_v1_gateway_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gateway/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gateway Turns
         * @description Gateway model calls, newest first.
         */
        get: operations["gateway_turns_v1_gateway_turns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guardrails/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guardrail Events
         * @description Blocks, redactions and budget alerts, newest first.
         */
        get: operations["guardrail_events_v1_guardrails_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guardrails/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guardrail Rules
         * @description The active blocking rules. The SDK and gateway fetch these and refresh them.
         */
        get: operations["guardrail_rules_v1_guardrails_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guardrails/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guardrail Summary
         * @description Blocks per rule and redactions per kind in the window.
         */
        get: operations["guardrail_summary_v1_guardrails_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest Stats */
        get: operations["ingest_stats_v1_ingest_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price Table
         * @description The price table that prices every stored span (USD per million tokens). The SDK and
         *     gateway use it to estimate spend for budgets.
         */
        get: operations["price_table_v1_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Spans
         * @description Queue a batch for writing and return at once; spans are readable shortly after.
         */
        post: operations["ingest_spans_v1_spans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traces */
        get: operations["list_traces_v1_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Facets */
        get: operations["trace_facets_v1_traces_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CostPoint */
        CostPoint: {
            /**
             * Bucket
             * Format: date-time
             * @description Start of the time bucket.
             */
            bucket: string;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Group
             * @description Model, client or service name (`other` when unknown).
             */
            group: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /**
         * CostSeries
         * @description Spend over time, one point per (bucket, group) with any cost. Buckets are aligned to
         *     ``bucket_seconds`` (chosen from the window: 5 min up to 1 day).
         */
        CostSeries: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Bucket Seconds */
            bucket_seconds: number;
            /**
             * Group By
             * @enum {string}
             */
            group_by: "model" | "client" | "service";
            /** Points */
            points: components["schemas"]["CostPoint"][];
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /**
         * DataInfo
         * @description What the database holds: the startup sample, real recorded data, or both.
         */
        DataInfo: {
            /** Real Data */
            real_data: boolean;
            /** Sample Data */
            sample_data: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** EvalCaseResult */
        EvalCaseResult: {
            /**
             * Baseline Passed
             * @description null when the case is new.
             */
            baseline_passed: boolean | null;
            /** Case */
            case: string;
            /** Checks */
            checks: components["schemas"]["EvalCheckResult"][];
            /** Cost Usd */
            cost_usd: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Output Preview */
            output_preview: string | null;
            /** Passed */
            passed: boolean;
            /** Trace Id */
            trace_id: string | null;
        };
        /** EvalCheckResult */
        EvalCheckResult: {
            /**
             * Check
             * @description e.g. `contains: refund`, `tool_called: lookup_order`.
             */
            check: string;
            /** Detail */
            detail?: string | null;
            /** Passed */
            passed: boolean;
        };
        /** EvalRun */
        EvalRun: {
            /** Baseline Cost Usd */
            baseline_cost_usd: number | null;
            /** Cases */
            cases: components["schemas"]["EvalCaseResult"][];
            /** Ci Url */
            ci_url?: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Duration Ms */
            duration_ms: number;
            /** Git Ref */
            git_ref?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Id */
            id: string;
            /** Model */
            model: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "regressed" | "error";
            /** Suite */
            suite: string;
        };
        /**
         * EvalRunIn
         * @description Body of ``POST /v1/evals/runs`` (sent by ``lucentpad eval``).
         */
        EvalRunIn: {
            /** Baseline Cost Usd */
            baseline_cost_usd: number | null;
            /** Cases */
            cases: components["schemas"]["EvalCaseResult"][];
            /** Ci Url */
            ci_url?: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Duration Ms */
            duration_ms: number;
            /** Git Ref */
            git_ref?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Model */
            model: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "regressed" | "error";
            /** Suite */
            suite: string;
        };
        /** EvalRunList */
        EvalRunList: {
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Runs
             * @description Newest first.
             */
            runs: components["schemas"]["EvalRunSummary"][];
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Baseline Cost Usd */
            baseline_cost_usd?: number | null;
            /** Ci Url */
            ci_url: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Failed */
            failed: number;
            /** Git Ref */
            git_ref: string | null;
            /** Git Sha */
            git_sha: string | null;
            /** Id */
            id: string;
            /** Passed */
            passed: number;
            /** Regressions */
            regressions: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "regressed" | "error";
            /** Suite */
            suite: string;
        };
        /** FacetValue */
        FacetValue: {
            /** Count */
            count: number;
            /** Value */
            value: string;
        };
        /** GatewayClientTotals */
        GatewayClientTotals: {
            /** Client */
            client: string;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Sessions */
            sessions: number;
            /** Turns */
            turns: number;
        };
        /**
         * GatewaySummary
         * @description Per-client totals over a time window, most expensive first.
         */
        GatewaySummary: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Clients */
            clients: components["schemas"]["GatewayClientTotals"][];
        };
        /**
         * GatewayTurn
         * @description One model call through the gateway (a ``kind=llm`` span with ``source=gateway``).
         */
        GatewayTurn: {
            /**
             * Client
             * @description `claude-code`, `copilot-cli`, `copilot-chat` or `other`.
             */
            client: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Failover
             * @description True when the request was retried on a fallback model.
             */
            failover: boolean;
            /** Input Preview */
            input_preview: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Model */
            model: string | null;
            /** Output Preview */
            output_preview: string | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Provider */
            provider: ("anthropic" | "openai") | null;
            /** Span Id */
            span_id: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "blocked";
            /** Streaming */
            streaming: boolean;
            /**
             * Trace Id
             * @description The session trace this turn belongs to.
             */
            trace_id: string;
            /** Ttfb Ms */
            ttfb_ms: number | null;
        };
        /** GatewayTurnList */
        GatewayTurnList: {
            /**
             * As Of
             * Format: date-time
             * @description Server time; pass it as `since` on the next live poll.
             */
            as_of: string;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Turns
             * @description Newest first.
             */
            turns: components["schemas"]["GatewayTurn"][];
        };
        /**
         * GuardrailEvent
         * @description A block (a ``kind=guardrail`` span), a redaction (a ``lucentpad.redaction`` event) or a
         *     budget alert (a ``lucentpad.budget.alert`` event).
         */
        GuardrailEvent: {
            /**
             * Budget Limit Usd
             * @description budget alerts
             */
            budget_limit_usd?: number | null;
            /**
             * Budget Scope
             * @description budget alerts: run | session
             */
            budget_scope?: string | null;
            /**
             * Budget Spent Usd
             * @description budget alerts
             */
            budget_spent_usd?: number | null;
            /** Client */
            client: string | null;
            /**
             * Count
             * @description redactions: how many values; blocks and budget alerts: 1
             */
            count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "block" | "redaction" | "budget";
            /**
             * Reason
             * @description blocks: why
             */
            reason: string | null;
            /**
             * Redaction Kind
             * @description redactions: email, api_key, card, ...
             */
            redaction_kind: string | null;
            /**
             * Rule
             * @description blocks: the rule id
             */
            rule: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "sdk" | "gateway";
            /** Span Id */
            span_id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Trace Id */
            trace_id: string;
        };
        /** GuardrailEventList */
        GuardrailEventList: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Events
             * @description Newest first.
             */
            events: components["schemas"]["GuardrailEvent"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * GuardrailRule
         * @description A blocking rule. ``prompt`` rules match the user's message (any keyword, case-insensitive,
         *     or the regex); ``tool`` rules match a tool call by name and a condition on its arguments,
         *     e.g. ``amount > 200`` (comparisons on argument fields; no code is evaluated).
         */
        GuardrailRule: {
            /**
             * Condition
             * @description tool rules, e.g. `amount > 200`
             */
            condition?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /**
             * Keywords
             * @description prompt rules
             */
            keywords?: string[];
            /**
             * Message
             * @description Shown to the caller when the rule blocks.
             */
            message: string;
            /**
             * Pattern
             * @description prompt rules: a regex
             */
            pattern?: string | null;
            /**
             * Tool
             * @description tool rules: the tool name
             */
            tool?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "prompt" | "tool";
        };
        /** GuardrailRuleCount */
        GuardrailRuleCount: {
            /** Blocks */
            blocks: number;
            /** Rule */
            rule: string;
        };
        /** GuardrailRules */
        GuardrailRules: {
            /** Rules */
            rules: components["schemas"]["GuardrailRule"][];
            /**
             * Source
             * @description Where the rules came from: a file path or `built-in`.
             */
            source: string;
            /**
             * Version
             * @description Changes whenever the rules change (for client caches).
             */
            version: string;
        };
        /**
         * GuardrailSummary
         * @description Counts for a window: blocks per rule, redactions per kind.
         */
        GuardrailSummary: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Blocks */
            blocks: components["schemas"]["GuardrailRuleCount"][];
            /**
             * Budget Alerts
             * @default 0
             */
            budget_alerts: number;
            /** Redactions */
            redactions: components["schemas"]["FacetValue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestAccepted */
        IngestAccepted: {
            /**
             * Accepted
             * @description Spans queued for writing (always the whole batch).
             */
            accepted: number;
        };
        /**
         * IngestStats
         * @description Counters of the ingest pipeline since the API started.
         */
        IngestStats: {
            /** Accepted Total */
            accepted_total: number;
            /** Queue Capacity */
            queue_capacity: number;
            /**
             * Queue Depth
             * @description Spans accepted but not yet written.
             */
            queue_depth: number;
            /**
             * Rejected Total
             * @description Spans refused with 429 because the queue was full.
             */
            rejected_total: number;
            /**
             * Write Errors Total
             * @description Spans dropped after the writer gave up retrying.
             */
            write_errors_total: number;
            /** Written Total */
            written_total: number;
        };
        /**
         * ModelPrice
         * @description USD per million tokens.
         */
        ModelPrice: {
            /** Cache Read */
            cache_read: number;
            /** Cache Write */
            cache_write: number;
            /** Input */
            input: number;
            /** Model */
            model: string;
            /** Output */
            output: number;
        };
        /** PriceTable */
        PriceTable: {
            /**
             * Checked
             * @description When the list prices were last checked (ISO date).
             */
            checked: string;
            /** Prices */
            prices: components["schemas"]["ModelPrice"][];
        };
        /** Span */
        Span: {
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean | string[];
            };
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Events */
            events?: components["schemas"]["SpanEvent"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "llm" | "tool" | "guardrail";
            /** Name */
            name: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "sdk" | "gateway";
            /** Span Id */
            span_id: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "error" | "blocked";
            /** Status Message */
            status_message?: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SpanBatch
         * @description Body of ``POST /v1/spans``.
         */
        SpanBatch: {
            /** Spans */
            spans: components["schemas"]["Span"][];
        };
        /**
         * SpanEvent
         * @description A point-in-time occurrence on a span, such as a failover or a budget alert.
         */
        SpanEvent: {
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean | string[];
            };
            /** Name */
            name: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** TraceDetail */
        TraceDetail: {
            /**
             * As Of
             * Format: date-time
             * @description Server time of this response; pass it as `since` on the next live poll.
             */
            as_of: string;
            /**
             * Spans
             * @description Spans ordered by start_time: all of them, or with `since` only those stored after it.
             */
            spans: components["schemas"]["Span"][];
            trace: components["schemas"]["TraceSummary"];
        };
        /**
         * TraceFacets
         * @description Value counts per filter. Each facet's counts apply every other filter but not its own,
         *     so ticking a value never hides its siblings. At most ``FACET_MAX_VALUES`` values per facet,
         *     by count descending, then value.
         */
        TraceFacets: {
            /** Client */
            client: components["schemas"]["FacetValue"][];
            /** Model */
            model: components["schemas"]["FacetValue"][];
            /** Name */
            name: components["schemas"]["FacetValue"][];
            /** Service */
            service: components["schemas"]["FacetValue"][];
            /** Source */
            source: components["schemas"]["FacetValue"][];
            /** Status */
            status: components["schemas"]["FacetValue"][];
        };
        /** TraceList */
        TraceList: {
            /**
             * As Of
             * Format: date-time
             * @description Server time of this response; pass it as `since` on the next live poll.
             */
            as_of: string;
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null when there are no more traces. Valid only with the same order and filters.
             */
            next_cursor: string | null;
            /** Traces */
            traces: components["schemas"]["TraceSummary"][];
        };
        /**
         * TraceSummary
         * @description One row of the traces list. Aggregates are computed over the trace's spans.
         */
        TraceSummary: {
            /** Client */
            client: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Input Preview
             * @description The run's first user message (root span's input, else the earliest llm span's); null when capture is off.
             */
            input_preview: string | null;
            /** Input Tokens */
            input_tokens: number;
            /** Llm Calls */
            llm_calls: number;
            /** Models */
            models: string[];
            /** Name */
            name: string;
            /**
             * Output Preview
             * @description The run's final answer (root span's output, else the latest llm span's).
             */
            output_preview: string | null;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Sample
             * @description Startup sample data (not something you recorded).
             * @default false
             */
            sample: boolean;
            /** Service Name */
            service_name: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "sdk" | "gateway";
            /** Span Count */
            span_count: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "blocked";
            /** Trace Id */
            trace_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    gateway_anthropic_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_anthropic_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_openai_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_openai_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    costs_v1_costs_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                group_by?: "model" | "client" | "service";
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    data_info_v1_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataInfo"];
                };
            };
        };
    };
    list_eval_runs_v1_evals_runs_get: {
        parameters: {
            query?: {
                suite?: string | null;
                limit?: number;
                cursor?: string | null;
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_eval_run_v1_evals_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_eval_run_v1_evals_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    gateway_summary_v1_gateway_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                /** @description Leave out the startup sample data. */
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    gateway_turns_v1_gateway_turns_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                /** @description Repeat for OR. */
                client?: string[] | null;
                limit?: number;
                cursor?: string | null;
                /** @description Live polling: turns stored after this time (previous `as_of`). */
                since?: string | null;
                /** @description Leave out the startup sample data. */
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayTurnList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guardrail_events_v1_guardrails_events_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                kind?: ("block" | "redaction" | "budget")[] | null;
                limit?: number;
                cursor?: string | null;
                since?: string | null;
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailEventList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guardrail_rules_v1_guardrails_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailRules"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guardrail_summary_v1_guardrails_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingest_stats_v1_ingest_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStats"];
                };
            };
        };
    };
    price_table_v1_pricing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceTable"];
                };
            };
        };
    };
    ingest_spans_v1_spans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpanBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Body larger than the ingest limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Ingest queue full; nothing from the batch was accepted. Retry after the `Retry-After` header (seconds). */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_traces_v1_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description `next_cursor` of the previous page. */
                cursor?: string | null;
                /** @description Sort key; `order` sets the direction. The cursor encodes both. */
                sort?: "started" | "duration" | "name" | "source" | "cost";
                order?: "desc" | "asc";
                /** @description Live polling: only traces that gained spans after this time (the previous response's `as_of`). Includes a few seconds of overlap, so expect traces already seen and merge by `trace_id`. Not combinable with `cursor`. */
                since?: string | null;
                /** @description Traces starting at or after this time (inclusive). */
                from?: string | null;
                /** @description Traces starting before this time (exclusive). */
                to?: string | null;
                /** @description Trace name; repeat for OR. */
                name?: string[] | null;
                status?: ("ok" | "error" | "blocked")[] | null;
                source?: ("sdk" | "gateway")[] | null;
                client?: string[] | null;
                /** @description Matches traces that used any of these models. */
                model?: string[] | null;
                /** @description `service.name`. */
                service?: string[] | null;
                /** @description Leave out the startup sample data. */
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Filter not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    trace_facets_v1_traces_facets_get: {
        parameters: {
            query?: {
                /** @description Traces starting at or after this time (inclusive). */
                from?: string | null;
                /** @description Traces starting before this time (exclusive). */
                to?: string | null;
                /** @description Trace name; repeat for OR. */
                name?: string[] | null;
                status?: ("ok" | "error" | "blocked")[] | null;
                source?: ("sdk" | "gateway")[] | null;
                client?: string[] | null;
                /** @description Matches traces that used any of these models. */
                model?: string[] | null;
                /** @description `service.name`. */
                service?: string[] | null;
                /** @description Leave out the startup sample data. */
                hide_sample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceFacets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trace_v1_traces__trace_id__get: {
        parameters: {
            query?: {
                /** @description Live polling: only spans stored after this time (the previous response's `as_of`), with a few seconds of overlap; merge by `span_id`. The summary is always current. */
                since?: string | null;
            };
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
