/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Spans */
        post: operations["ingest_spans_v1_spans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traces */
        get: operations["list_traces_v1_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestAccepted */
        IngestAccepted: {
            /** Accepted */
            accepted: number;
        };
        /** Span */
        Span: {
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean | string[];
            };
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Events */
            events?: components["schemas"]["SpanEvent"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "llm" | "tool" | "guardrail";
            /** Name */
            name: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "sdk" | "gateway";
            /** Span Id */
            span_id: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "error" | "blocked";
            /** Status Message */
            status_message?: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SpanBatch
         * @description Body of ``POST /v1/spans``.
         */
        SpanBatch: {
            /** Spans */
            spans: components["schemas"]["Span"][];
        };
        /**
         * SpanEvent
         * @description A point-in-time occurrence on a span, such as a failover or a budget alert.
         */
        SpanEvent: {
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean | string[];
            };
            /** Name */
            name: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** TraceDetail */
        TraceDetail: {
            /**
             * Spans
             * @description All spans in the trace, ordered by start_time.
             */
            spans: components["schemas"]["Span"][];
            trace: components["schemas"]["TraceSummary"];
        };
        /** TraceList */
        TraceList: {
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null when there are no more traces.
             */
            next_cursor: string | null;
            /** Traces */
            traces: components["schemas"]["TraceSummary"][];
        };
        /**
         * TraceSummary
         * @description One row of the traces list. Aggregates are computed over the trace's spans.
         */
        TraceSummary: {
            /** Client */
            client: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Duration Ms */
            duration_ms: number;
            /** Input Tokens */
            input_tokens: number;
            /** Llm Calls */
            llm_calls: number;
            /** Models */
            models: string[];
            /** Name */
            name: string;
            /** Output Tokens */
            output_tokens: number;
            /** Service Name */
            service_name: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "sdk" | "gateway";
            /** Span Count */
            span_count: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "blocked";
            /** Trace Id */
            trace_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_spans_v1_spans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpanBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Ingest queue full; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented until M1. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_traces_v1_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                source?: ("sdk" | "gateway") | null;
                status?: ("ok" | "error" | "blocked") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_v1_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
